#!/bin/sh
for d in $@; do
  (
    set -ex
    cd $d
    if ! git remote | grep -Fq upstream; then
      echo 'no upstream' >&2
      return 1
    fi
    if ! git diff --quiet; then
      echo 'Changes not staged for commit' >&2
      return 1
    fi
    branch=$(git branch | sed -e /'^ '/d -e s/'^. '//)
    git fetch upstream $branch
    git merge upstream/$branch && git push
    echo
  )
done
