#!/bin/sh
set -ux

impl() (
  set -e
  cd "$1"

  git diff --quiet
  git status -u no | head -n1 | grep -Fq 'On branch '
  git remote | grep -Fq upstream
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' 0 1 2 15
  git remote show upstream > "$tmp"

  branch=$(< "$tmp" sed -n -e '/HEAD branch/s/.*: //p')
  [ -n "$branch" ]
  if < "$tmp" sed -e '0,/^ *Local refs\? configured for /d' | \
    grep -q "^ *$branch pushes to $branch (up to date)"; then
    exit 0
  fi
  git fetch upstream "$branch"
  if [ "$(git branch | sed -e '/^ /d;s/^. //p')" = "$branch" ]; then
    if ! git merge upstream/"$branch"; then
      git merge --abort
      exit 1
    fi
    git push
  else
    git switch "$branch"
    if ! git merge upstream/"$branch"; then
      git merge --abort
      git switch -
      exit 1
    fi
    if ! git push; then
      git switch -
      exit 1
    fi
    git switch -
  fi
)

for d; do
  impl "$d"
done
