#!/bin/bash
set -e
if [ $# -ne 2 ]; then
  echo "usage: ${0##*/} bib dest" >&2
  exit 1
fi
bib=$1
dest=$2

if [ ! -f "${bib}" ]; then
  echo "error: ${bib} is not a file" >&2
  exit 1
fi

sed -i \
  -e '/^\s*$/d' \
  -e 's/\s*$//' \
  -e 's/,\+$/,/' \
  -e 's/^\s*@/@/' \
  "${bib}"
echo >> "${bib}"

key="$(< ${bib} sed -e '2,$d' -e 's/^@[a-zA-Z]\+{\s*//' -e 's/\s*,\s*$//')"

if [ -d "${dest}" ]; then
  bibbase="${bib##*/}"
  if [ "${bibbase%.bibtex}" != "${bibbase}" ]; then
    dest="${dest}/${bibbase%.bibtex}.bib"
  elif [ "${bibbase}" = 'RSC_.bib' ] || [ "${bibbase}" = 'science.bib' ]; then
    dest="${dest}/${key}.bib"
  fi
fi
mv -v "${bib}" "${dest}"

echo "${key}"
