#!/bin/sh
set -ux

check() {
  git diff --quiet --ignore-submodules &&
  git status -u no | head -n 1 | grep -Fq 'On branch '
}

impl() (
  set -e
  cd "$1"

  check

  remote=
  if git remote | grep -Fq upstream; then
    remote=upstream
  elif git remote | grep -Fq origin; then
    remote=origin
  fi
  [ -n "$remote" ]

  headbranch=$(git remote show "$remote" | sed -n -e '/HEAD branch/s/.*: //p')
  [ -n "$headbranch" ]
  git fetch "$remote" "$headbranch"

  set +e
  git worktree list --porcelain | sed -n -E -e '/^worktree\s+/s///p' |
  while IFS= read -r wt; do
    cd "$wt" || continue
    check || continue
    if ! git rebase "$remote/$headbranch"; then
      git rebase --abort
    fi
  done

  for b in $(git branch | sed -n -e '/^[^+] /s///p'); do
    (
      trap 'git restore .; git switch -' 0
      git switch "$b"
      if ! git rebase "$remote/$headbranch"; then
        git rebase --abort
      fi
      if [ "$b" = "$headbranch" ]; then
        git push
      fi
    )
  done
)

for d; do
  impl "$d"
done
