#!/bin/sh
set -ux

impl() (
  set -e
  cd "$1"

  git diff --quiet
  git status -u no | head -n1 | grep -Fq 'On branch '
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' 0

  remote=
  if git remote | grep -Fq upstream; then
    remote=upstream
  elif git remote | grep -Fq origin; then
    remote=origin
  fi

  [ "$remote" ]
  headbranch=$(git remote show "$remote" | sed -n -e '/HEAD branch/s/.*: //p')
  git fetch "$remote" "$headbranch"

  set +e
  for b in $(git branch | sed -e 's/^..//'); do
    (
      trap 'git switch -' 0
      git switch "$b"
      if ! git rebase "$remote/$headbranch"; then
        git rebase --abort
      fi
      if [ "$b" = "$headbranch" ]; then
        git push
      fi
    )
  done
)

for d; do
  impl "$d"
done
