#!/usr/bin/env python3
import argparse
import scipy.io


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source")
    parser.add_argument("target")
    parser.add_argument(
        "--symmetry", "-s", choices=["symmetric", "skew-symmetric", "hermitian"]
    )
    args = parser.parse_args()

    m = scipy.io.mmread(args.source)
    scipy.io.mmwrite(args.target, m, symmetry=args.symmetry)


if __name__ == "__main__":
    main()
